Directory three of the project:

```
├── code
├── data
├── jmxs
├── model
├── pcaps
└── results
```

The working dir of the script is the code/ directory

The code will be used to extract data to instrument the model. The data has been obtained from the system executing the application. The perform N readings in a observation time interval T. 

    1. read data from the data dir/ - 
    
    ```
    ├── 10-38
    │   ├── containers_pre.json
    │   ├── containers_post.json
    │   ├── energy.csv
    │   ├── system_pre.json
    │   ├── system_post.json
    │   └── requests.jtl
    ├── 11-38
    │   ├── containers_pre.json
    │   ├── containers_post.json
    │   ├── energy.csv
    │   ├── system_pre.json
    │   ├── system_post.json
    │   └── requests.jtl
    ```
       
    The name of the directory contains two numbers. The former describes the ith reading while the second one the population of customers operating while reading performance and energy values.

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
from itertools import chain
import csv, json, glob, os

In [2]:
IPSPATH = "experiment_configuration_data/ips.csv"
CONVERSATIONSPATH = "experiment_configuration_data/conversations.csv"
ips = pd.read_csv(IPSPATH)
conversations = pd.read_csv(CONVERSATIONSPATH)

In [3]:
for i, x in ips.iterrows():
    conversations = conversations.replace(x['ip'], x['container'])

In [4]:
conversations = pd.read_csv("experiment_configuration_data/conversations_names.csv")

In [5]:
conversations

            source        destination
0   145.108.225.16      145.108.225.7
1   145.108.225.16                 ui
2               ui               auth
3             auth  verification-code
4               ui  verification-code
5               ui             travel
6           travel         ticketinfo
7       ticketinfo              basic
8            basic            station
9           travel              route
10           basic              train
11           basic              route
12           basic              price
13          travel              order
14          travel               seat
15            seat              order
16          travel              train
17            seat             config
18              ui          assurance
19              ui           contacts
20              ui               food
21            food           food-map
22            food             travel
23            food            station
24              ui           preserve
25        preserve           security
26        security              order
27        security        order-other
28        preserve           contacts
29        preserve             travel
30        preserve            station
31        preserve         ticketinfo
32        preserve               seat
33        preserve              order
34        preserve          assurance
35        preserve               food
36        preserve            consign
37         consign      consign-price
38        preserve               user

In [6]:
conversations[(conversations == 'travel').any(axis=1)]

      source destination
5         ui      travel
6     travel  ticketinfo
9     travel       route
13    travel       order
14    travel        seat
16    travel       train
22      food      travel
29  preserve      travel

In [7]:
DATA = f"../model/results-single"
DIRS = list(map(lambda x: f"{DATA}/{x}", os.listdir(DATA)))

In [8]:
DIRS75 = list(filter(lambda x: x.find("-75") != -1, DIRS))

In [9]:
def get_energy_stats(trials):
    time   = np.array([len(x['time']) for x in trials])
    energy = np.array(
        [np.trapz(x['power'], x['time']) for x in trials]
    )
    e = energy/time
    
    print(
            f"# Energy Per Visit(Joule/Visit):\n",
            f"## Mean:\t\t\t{energy.mean()}", 
            f"## Min-Max:\t\t\t[{energy.min()}, {energy.max()}]",
            f"## Var:\t\t\t\t{energy.var()}", 
            f"## Std:\t\t\t\t{energy.std()}", 
            '\n'
            f"# Average Response Time:\t{time.mean()}",
            f"# e (Joule/s):\t\t\t{e.mean()}, [{e.min()}, {e.max()}]",
            sep='\n'
         )

In [10]:
ENERGYFILES = [f"{x}/energy.csv" for x in DIRS]

In [11]:
energy_values = [
    pd.read_csv(x, names = ["time", "power"]) for x in ENERGYFILES
]

In [12]:
get_energy_stats(energy_values)

# Energy Per Visit(Joule/Visit):

## Mean:			742.3410799999999
## Min-Max:			[710.1889000000001, 807.83495]
## Var:				1016.1577052245999
## Std:				31.877228631494926

# Average Response Time:	13.6
# e (Joule/s):			54.60543380586081, [52.516392857142854, 55.63896071428571]

In [13]:
from helpers.stats import SystemStats
from helpers.stats import ContainerStats

In [14]:
def calculate_containers_utilization(DIRS):
    rows = []
    for x in DIRS:
        f1, f2 = glob.glob(f"{x}/containers_*.json")
        data = ContainerStats(f2, f1).data
        rows.append(
            {k: [v['cpu'], v['disk'], v['io']] for k,v in data.items()}
        )

    return pd.DataFrame.from_records(rows)

def calculate_system_utilization(DIRS):
    rows = []
    for x in DIRS:
        f1, f2 = glob.glob(f"{x}/system_*.json")
        data = SystemStats(f2, f1).data[0]
        rows.append(
            {'cpu': data['cpu0'], 'duration': data['duration']}
        )

    return pd.DataFrame.from_records(rows)

In [15]:
containers_stats = calculate_containers_utilization(DIRS75)
system_stats = calculate_system_utilization(DIRS75)
mean_duration = system_stats['duration'].mean()
mean_cpu = system_stats['cpu'].mean()
arrival_rate = 1/mean_duration

In [16]:
print(f"mean_cpu: {mean_cpu}", f"mean_duration: {mean_duration}", f"arrival_rate: {arrival_rate}")

mean_cpu: 46.1371 mean_duration: 14.20819113254547 arrival_rate: 0.0703819360727339

In [17]:
#containers_stats.drop('docker', axis=1).head(1).values.sum()

In [18]:
for k in containers_stats.keys():
    cpu_util = np.array([v[0] for v in containers_stats[k]])
    #disk_util = np.array([v[1] for v in containers_stats[k]])
    io_util = np.array([v[2] for v in containers_stats[k]])
    mean_cpu = cpu_util.mean()
    mean_io = io_util.mean()
    #mean_disk = disk_util.mean()
    print(f"{k:<50} {mean_cpu:<20} {((mean_cpu/100)/arrival_rate):<20} {mean_io}")

baseline-ts-consign-price-service-1                0.11177240944098657  0.01588083756682667  0.4
baseline-ts-price-service-1                        0.38930354406703244  0.05531299162681736  0.2
baseline-ts-contacts-service-1                     0.6713189663401817   0.09538228184664163  0.4
baseline-ts-order-service-1                        1.289217592962197    0.18317449972247105  0.1
baseline-ts-route-service-1                        1.4897847942377458   0.2116714710288982   0.2
baseline-ts-travel-service-1                       3.2848188931444207   0.4667133466959239   0.0
baseline-ts-user-service-1                         0.16118791545888736  0.02290188711096453  0.6
baseline-ts-config-service-1                       0.4372045481392325   0.062118857839803934 0.0
baseline-ts-ticketinfo-service-1                   1.8634332559498366   0.26476015863276803  0.0
baseline-ts-order-other-service-1                  0.14299201342917522  0.020316578572292306 0.0
baseline-ts-station-service-1                      2.7069385776592396   0.3846070069544326   0.1
baseline-ts-preserve-service-1                     1.2000141396216717   0.1705003025750182   0.0
baseline-ts-assurance-service-1                    0.3439407315495797   0.04886775652123941  0.0
baseline-ts-basic-service-1                        2.5225633438826036   0.3584106213383706   0.0
baseline-ts-security-service-1                     0.2810519584393324   0.03993239943682261  0.0
baseline-ts-consign-service-1                      0.2287777267348292   0.032505176683177116 0.4
baseline-ts-train-service-1                        1.0621711940066676   0.15091531339930772  0.0
baseline-ts-verification-code-service-1            0.23690495129544722  0.0336599082825209   0.5
baseline-ts-food-service-1                         0.6385312614748442   0.09072374207139955  0.0
baseline-ts-seat-service-1                         1.312803744340399    0.1865256651910975   0.0
baseline-ts-food-map-service-1                     0.36308660547285654  0.051588038882254765 0.0
baseline-ts-ui-dashboard-1                         0.2223042641781932   0.031585414750236504 0.0
baseline-ts-auth-service-1                         6.488569785249998    0.921908396856915    0.0
baseline-ts-inside-payment-mongo-1                 0.09255643905076526  0.013150595765810685 0.0
baseline-ts-order-mongo-1                          0.20534143883421052  0.029175304103883585 69.2
baseline-ts-payment-mongo-1                        0.08820992523299209  0.012533034774978974 0.0
baseline-ts-price-mongo-1                          0.11788336331445662  0.016749093573190987 0.8
baseline-ts-consign-mongo-1                        0.10576392818371991  0.015027141065631055 71.7
baseline-ts-route-mongo-1                          0.17197327025119932  0.024434290934179363 0.4
baseline-ts-food-map-mongo-1                       0.12706559756141173  0.018053722965236416 0.4
baseline-ts-contacts-mongo-1                       0.15009880337712558  0.02132632487148562  53.2
baseline-ts-ticket-office-mongo-1                  0.0907713144421765   0.01289696184946829  0.4
baseline-ts-train-mongo-1                          0.1900309723625379   0.026999963764304045 0.6
baseline-ts-assurance-mongo-1                      4.3898253510149745   0.6237147762571428   84.1
baseline-ts-travel-mongo-1                         0.1692607523835562   0.02404889121104018  0.4