Directory three of the project:

```
├── code
├── data
├── jmxs
├── model
├── pcaps
└── results
```

The working dir of the script is the code/ directory

The code will be used to extract data to instrument the model. The data has been obtained from the system executing the application. The perform N readings in a observation time interval T. 

    1. read data from the data dir/ - 
    
    ```
    ├── 10-38
    │   ├── containers_pre.json
    │   ├── containers_post.json
    │   ├── energy.csv
    │   ├── system_pre.json
    │   ├── system_post.json
    │   └── requests.jtl
    ├── 11-38
    │   ├── containers_pre.json
    │   ├── containers_post.json
    │   ├── energy.csv
    │   ├── system_pre.json
    │   ├── system_post.json
    │   └── requests.jtl
    ```
       
    The name of the directory contains two numbers. The former describes the ith reading while the second one the population of customers operating while reading performance and energy values.

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
from itertools import chain
import csv, json, glob, os

In [2]:
IPSPATH = "experiment_configuration_data/ips.csv"
CONVERSATIONSPATH = "experiment_configuration_data/conversations.csv"
ips = pd.read_csv(IPSPATH)
conversations = pd.read_csv(CONVERSATIONSPATH)

In [3]:
for i, x in ips.iterrows():
    conversations = conversations.replace(x['ip'], x['container'])

In [4]:
conversations = pd.read_csv("experiment_configuration_data/conversations_names.csv")

In [5]:
conversations

            source        destination
0   145.108.225.16      145.108.225.7
1   145.108.225.16                 ui
2               ui               auth
3             auth  verification-code
4               ui  verification-code
5               ui             travel
6           travel         ticketinfo
7       ticketinfo              basic
8            basic            station
9           travel              route
10           basic              train
11           basic              route
12           basic              price
13          travel              order
14          travel               seat
15            seat              order
16          travel              train
17            seat             config
18              ui          assurance
19              ui           contacts
20              ui               food
21            food           food-map
22            food             travel
23            food            station
24              ui           preserve
25        preserve           security
26        security              order
27        security        order-other
28        preserve           contacts
29        preserve             travel
30        preserve            station
31        preserve         ticketinfo
32        preserve               seat
33        preserve              order
34        preserve          assurance
35        preserve               food
36        preserve            consign
37         consign      consign-price
38        preserve               user

In [6]:
conversations[(conversations == 'travel').any(axis=1)]

      source destination
5         ui      travel
6     travel  ticketinfo
9     travel       route
13    travel       order
14    travel        seat
16    travel       train
22      food      travel
29  preserve      travel

In [7]:
DATA = f"../model/results"
DIRS = list(map(lambda x: f"{DATA}/{x}", os.listdir(DATA)))
CUST = 75

In [8]:
DIRS = list(filter(lambda x: x.find(f"-{CUST}") != -1, DIRS))

In [9]:
DIRS

['../model/results/10-75',
 '../model/results/9-75',
 '../model/results/5-75',
 '../model/results/2-75',
 '../model/results/3-75',
 '../model/results/4-75',
 '../model/results/7-75',
 '../model/results/1-75',
 '../model/results/8-75',
 '../model/results/6-75']

In [10]:
def get_energy_stats(trials):
    time   = np.array([len(x['time']) for x in trials])
    energy = np.array(
        [np.trapz(x['power'], x['time']) for x in trials]
    )
    e = energy/time
    
    print(
            f"# Energy Per Visit(Joule/Visit):\n",
            f"## Mean:\t\t\t{energy.mean()}", 
            f"## Min-Max:\t\t\t[{energy.min()}, {energy.max()}]",
            f"## Var:\t\t\t\t{energy.var()}", 
            f"## Std:\t\t\t\t{energy.std()}", 
            '\n'
            f"# Average Response Time:\t{time.mean()}",
            f"# e (Joule/s):\t\t\t{e.mean()}, [{e.min()}, {e.max()}]",
            sep='\n'
         )

In [11]:
ENERGYFILES = [f"{x}/energy.csv" for x in DIRS]

In [12]:
energy_values = [
    pd.read_csv(x, names = ["time", "power"]) for x in ENERGYFILES
]

In [13]:
get_energy_stats(energy_values)

# Energy Per Visit(Joule/Visit):

## Mean:			746.967985
## Min-Max:			[723.2476499999998, 787.6673499999999]
## Var:				548.6473727090258
## Std:				23.423222935988672

# Average Response Time:	13.5
# e (Joule/s):			55.35127145604396, [53.17049285714286, 56.26195357142857]

In [14]:
from helpers.stats import SystemStats
from helpers.stats import ContainerStats

In [15]:
def calculate_containers_utilization(DIRS):
    rows = []
    for x in DIRS:
        f1, f2 = glob.glob(f"{x}/containers_*.json")
        data = ContainerStats(f2, f1).data
        rows.append(
            {k: [v['cpu'], v['disk'], v['io']] for k,v in data.items()}
        )

    return pd.DataFrame.from_records(rows)

def calculate_system_utilization(DIRS):
    rows = []
    for x in DIRS:
        f1, f2 = glob.glob(f"{x}/system_*.json")
        data = SystemStats(f2, f1).data[0]
        rows.append(
            {'cpu': data['cpu0'], 'disk': data['disk'], 'io': data['io'], 'duration': data['duration']}
        )

    return pd.DataFrame.from_records(rows)

In [16]:
containers_stats = calculate_containers_utilization(DIRS)
system_stats     = calculate_system_utilization(DIRS)
mean_duration    = system_stats['duration'].mean()
mean_disk        = system_stats['disk'].mean()
mean_io          = system_stats['io'].mean()
sys_mean_cpu     = system_stats['cpu'].mean()
arrival_rate     = CUST/mean_duration

In [17]:
print(
    f"mean_cpu: {sys_mean_cpu}",
    f"mean_disk: {mean_disk}",
    f"mean_duration: {mean_duration}",
    f"mean_io: {mean_io}",
    f"arrival_rate: {arrival_rate}"
)

mean_cpu: 46.7996 mean_disk: 16.0377 mean_duration: 14.224926829338074 mean_io: 570.5 arrival_rate: 5.272434853254705

In [18]:
#containers_stats.drop('docker', axis=1).head(1).values.sum()

In [23]:
tot = 0
for k in containers_stats.keys():
    cpu_util  = np.array([v[0] for v in containers_stats[k]])
    disk_util = np.array([v[1] for v in containers_stats[k]])
    io_util   = np.array([v[2] for v in containers_stats[k]])
    mean_cpu  = cpu_util.mean()
    mean_io   = io_util.mean()
    mean_disk = disk_util.mean()
    
    tot += mean_cpu

    print(
        f"{k:<50} {mean_cpu:<20} {((mean_cpu/100)/arrival_rate):<25}" 
    )
   
delta_util = (sys_mean_cpu - tot) / 100
print(f"total application utilization: {tot:>34} {delta_util} {delta_util/arrival_rate}")

baseline-ts-consign-price-service-1                0.10676923155236939  0.0002025046008609478
baseline-ts-price-service-1                        0.37798032093966805  0.0007168989877728666
baseline-ts-contacts-service-1                     0.6912866348222465   0.0013111335731261075
baseline-ts-order-service-1                        1.623839920607007    0.0030798672070923767
baseline-ts-route-service-1                        1.5439266339204405   0.002928299119651266
baseline-ts-travel-service-1                       3.275018780153495    0.0062115870016522
baseline-ts-user-service-1                         0.17224972971575278  0.0003266986402106458
baseline-ts-config-service-1                       0.4387610061557397   0.0008321790944176199
baseline-ts-ticketinfo-service-1                   1.9061076914482988   0.0036152323252920753
baseline-ts-order-other-service-1                  0.15016305863928048  0.0002848078028817823
baseline-ts-station-service-1                      2.77449520282748     0.005262265499809387
baseline-ts-preserve-service-1                     1.2290635332836468   0.002331111843942346
baseline-ts-assurance-service-1                    0.3644953560816728   0.000691322635986043
baseline-ts-basic-service-1                        2.548398810475439    0.00483343821479804
baseline-ts-security-service-1                     0.3012358520251764   0.0005713410604575261
baseline-ts-consign-service-1                      0.2262122163383616   0.0004290469633754118
baseline-ts-train-service-1                        1.077259188516493    0.0020431910843838968
baseline-ts-verification-code-service-1            0.22720528612713933  0.0004309304760529837
baseline-ts-food-service-1                         0.6546960548651568   0.0012417337967884213
baseline-ts-seat-service-1                         1.4082550475374034   0.0026709766677687433
baseline-ts-food-map-service-1                     0.3754393671572784   0.000712079670222037
baseline-ts-ui-dashboard-1                         0.21905693884377678  0.00041547585686820134
baseline-ts-auth-service-1                         6.362001763241176    0.012066534609363406
baseline-ts-inside-payment-mongo-1                 0.09840852218752719  0.00018664720366678221
baseline-ts-order-mongo-1                          0.2520594482127276   0.00047807029432925057
baseline-ts-payment-mongo-1                        0.09851262148148551  0.0001868446443120546
baseline-ts-price-mongo-1                          0.126673723990646    0.00024025659399556083
baseline-ts-consign-mongo-1                        0.11901378219750611  0.0002257283124589737
baseline-ts-route-mongo-1                          0.1829865222694261   0.0003470626520050171
baseline-ts-food-map-mongo-1                       0.1297571359656946   0.000246104768626197
baseline-ts-contacts-mongo-1                       0.1611022402708991   0.00030555567731946413
baseline-ts-ticket-office-mongo-1                  0.09718984959276104  0.00018433579986818649
baseline-ts-train-mongo-1                          0.19005750072938155  0.0003604738721656427
baseline-ts-assurance-mongo-1                      4.711196265828865    0.008935522954675515
baseline-ts-travel-mongo-1                         0.17798020780263887  0.00033756739107505644
total application utilization:                  34.39885544580405 0.12400744554195946 0.023519957855033323